spring.profiles.active=test
spring.jpa.open-in-view=false

#Variaveis que sera usadas nos configs

#Username e Password da Authorization
security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}

#Tempo de duracao do Token em Long
security.jwt.duration=${JWT_DURATION:86400}

#Hosts liberados para acessar o sistema
cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}